export const FETCH_CURRENT_WEATHER = "FETCH_CURRENT_WEATHER";
export const FETCH_FORECAST_WEATHER = "FETCH_CURRENT_WEATHER";

export const FETCH_WEATHER_PENDING = "FETCH_WEATHER_PENDING";
export const FETCH_WEATHER_ERROR = "FETCH_CURRENT_WEATHER";

export const SET_CITY = "SET_CITY";
